// Render docs/VENUES.md from the venue sweep. Pure formatting — no new chain reads.
import fs from "node:fs";
const v = JSON.parse(fs.readFileSync(new URL("./venues.json", import.meta.url)));
const L = [];
const p = (s = "") => L.push(s);

const tickers = Object.keys(v.venues);
let totV3 = 0, totV4 = 0, totR = 0, actV3 = 0, actV4 = 0;
for (const t of tickers) for (const x of v.venues[t]) {
  if (x.kind === "v3") { totV3++; if (x.active) actV3++; }
  if (x.kind === "v4") { totV4++; if (x.active) actV4++; }
  if (x.kind === "rialto") totR++;
}
const routable = (t) => v.venues[t].filter((x) => (x.kind === "rialto" ? x.capSize > 0 : x.active));

p("# VENUES — Robinhood Chain (4663)");
p();
p(`Generated by \`script/recon/venue-map.mjs\` at block **${v.block}**, ${v.at}.`);
p("All rows are read back from the chain by `eth_call`. Regenerate before quoting any of it.");
p();
p("## Method");
p();
p("- **v3** — `UniswapV3Factory.getPool(token, quote, fee)` for fee tiers 100/500/3000/10000 against USDG and WETH.");
p("- **v4** — poolId derived as `keccak256(abi.encode(currency0, currency1, fee, tickSpacing, hooks=0))`,");
p("  then probed through `StateView`. Existence is `slot0.sqrtPriceX96 != 0`, **not** `getLiquidity != 0`:");
p("  `getLiquidity` returns only active in-range liquidity, and at least one live pool (SPY 500/10) is");
p("  initialised with zero active liquidity. Hook pools are **not** discoverable this way — see Limitations.");
p("- **Rialto** — propAMM pairs probed with `getAmountOut(bool,uint256)` at rising sizes. A `0` return is the");
p("  maker declining that size, per the Rialto spec; it is recorded as a cap, never as an error.");
p();
p("## Totals");
p();
p("| | initialised | with active liquidity |");
p("|---|---|---|");
p(`| Uniswap v3 pools | ${totV3} | ${actV3} |`);
p(`| Uniswap v4 pools (hookless) | ${totV4} | ${actV4} |`);
p(`| Rialto propAMM pairs | ${totR} | see cap table |`);
p(`| **Total venues** | **${totV3 + totV4 + totR}** | **${actV3 + actV4}** + makers |`);
p();
const splittable = tickers.filter((t) => routable(t).length >= 2);
p(`**${splittable.length} of ${tickers.length} tickers have 2 or more routable venues** — i.e. a split is possible at all.`);
p(`**${tickers.filter((t) => routable(t).length >= 4).length} have 4 or more.**`);
p();
p("## Per ticker");
p();
p("| ticker | routable | v3 (active/init) | v4 (active/init) | rialto cap | venue detail |");
p("|---|---|---|---|---|---|");
for (const t of tickers) {
  const all = v.venues[t];
  const v3 = all.filter((x) => x.kind === "v3");
  const v4 = all.filter((x) => x.kind === "v4");
  const r = all.find((x) => x.kind === "rialto");
  const detail = [
    ...v3.filter((x) => x.active).map((x) => `v3:${x.quote}/${x.fee}`),
    ...v4.filter((x) => x.active).map((x) => `v4:${x.quote}/${x.fee}`),
    ...(r && r.capSize > 0 ? [`rialto≤${r.capSize}`] : []),
  ].join(" ") || "—";
  p(`| ${t} | ${routable(t).length} | ${v3.filter((x) => x.active).length}/${v3.length} | ${v4.filter((x) => x.active).length}/${v4.length} | ${r ? (r.capSize > 0 ? r.capSize + " units" : "refuses all") : "—"} | ${detail} |`);
}
p();
p("## Rialto propAMM size ladder");
p();
p("Units are whole tokens of the stock leg. `refused` is a `0` return — the maker declining, per spec.");
p();
const rs = tickers.map((t) => [t, v.venues[t].find((x) => x.kind === "rialto")]).filter(([, r]) => r);
const sizes = rs.length ? rs[0][1].quotes.map((q) => q.size) : [];
p("| ticker | " + sizes.join(" | ") + " | cap |");
p("|---|" + sizes.map(() => "---").join("|") + "|---|");
for (const [t, r] of rs) {
  const cells = r.quotes.map((q) => (q.status === "ok" ? "ok" : q.status === "refused" ? "·" : "rv"));
  p(`| ${t} | ${cells.join(" | ")} | ${r.capSize} |`);
}
p();
p("## Limitations");
p();
p("- Hook pools (v4 pools with a non-zero `hooks` address) are **not** enumerated. poolId derivation needs the");
p("  hook address as an input, so they cannot be brute-forced, and both public 4663 RPCs refuse `eth_getLogs`.");
p("  Any hook pool must be added to the registry by address. This is an honest gap in coverage, not a claim of none.");
p("- Uniswap v2 is deployed on 4663 (`UniswapV2Factory`) but is not swept here.");
p("- `active` is a snapshot of in-range liquidity at one block and moves constantly.");
fs.writeFileSync("docs/VENUES.md", L.join("\n") + "\n");
console.log(L.slice(0, 40).join("\n"));
console.log("\n... wrote docs/VENUES.md");
